{{- if .Values.truststore -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kafka_monitor.fullname" . }}
  labels:
    app: {{ template "kafka_monitor.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    team: {{ .Values.team }}
type: Opaque
data:
  truststore: {{ .Values.truststore.jks | quote }}
{{- end -}}
