---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "kafka_monitor.name" . }}
    component: {{ .Values.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    team: {{ .Values.team }}
  name: {{ template "kafka_monitor.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "kafka_monitor.name" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: jolokia
    protocol: TCP
    port: 8778
    targetPort: 8778

