apiVersion: v1
name: kafka-monitor
description: Kafka monitor
version: 1.0.0
sources:
  - https://github.com/nais/kafka-monitor
  - https://github.com/linkedin/kafka-monitor
maintainers:
  - name: Terje Sannum
    email: terje.sannum@nav.no
